# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: aws-serverless

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    sqs_url:
      Ref: Messages

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: SNSDispatcherFunction.handler
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: / 
          method: get
          cors: true
      - s3: mycools3bucket
  
  sqsProducer:
    handler: sqs_producer.handler
    events:
      - http: 
          path: /sqsproducer
          method: get
          cors: true 
  sqsConsumer:
    handler: sqs_consumer.handler
    events:
      - http:
          path: /sqsconsumer
          method: get
          cors: true

custom:
  sqs: mycoolnewqueue2


resources:
  Resources:
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mycoolnewbucket2
    TodosDynamoDbTable: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: mycoolnewtable3
    Messages:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs}
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: 60
